// @ts-nocheck
import JSZip from 'jszip';
const contacts=JSON.parse(document.querySelector<HTMLScriptElement>('#contacts-data')!.textContent||'{}');
const required=JSON.parse(document.querySelector<HTMLScriptElement>('#required-data')!.textContent||'[]');
const form=document.querySelector<HTMLFormElement>('#city-wizard')!,steps=[...document.querySelectorAll<HTMLElement>('.wizard-step')],dots=[...document.querySelectorAll<HTMLElement>('#stepper li')];let current=0;let detectedColumns=[];let uploaded=[];const canonical=required.map(x=>x[0]);
const stateKey='courtscope-city-onboarding-v1';
function formState(){return Object.fromEntries(new FormData(form).entries())}
function setStep(i:number){current=Math.max(0,Math.min(steps.length-1,i));steps.forEach((s,n)=>s.hidden=n!==current);dots.forEach((d,n)=>d.classList.toggle('active',n===current));document.querySelector<HTMLButtonElement>('#back').disabled=current===0;document.querySelector<HTMLButtonElement>('#next').textContent=current===steps.length-1?'Review complete':'Next step';if(current===2)renderRequest();if(current===4)renderReadiness();window.scrollTo({top:0,behavior:'smooth'})}
function contact(){const id=document.querySelector<HTMLSelectElement>('#court-select').value;const c=contacts.jurisdictions.find(x=>x.id===id);const el=document.querySelector<HTMLElement>('#contact-card');if(!c){el.innerHTML='<strong>Custom court:</strong> add verified contact information in the communication notes before sending a request.';return}el.innerHTML=`<strong>${c.label}</strong><br>${c.clerk}<br>${c.address}<br>Phone: ${c.phones.join(' · ')}<br>Email: <a href="mailto:${c.email}">${c.email}</a><br>${c.hours}<br><a href="${c.official_url}" target="_blank" rel="noopener">Verify official contact</a> · <a href="${c.records_url}" target="_blank" rel="noopener">Records information</a>`}
document.querySelector<HTMLSelectElement>('#court-select').addEventListener('change',contact);contact();
function requestText(){const s=formState(), c=contacts.jurisdictions.find(x=>x.id===s.court);const fields=required.map(x=>`- ${x[1]} (${x[2]})`).join('\n');return `Subject: Public records request for machine-readable criminal court case and sentencing data\n\nTo: ${c?.email||'[Public Records Coordinator]'}\n\nHello,\n\nCourtScope is an independent open-source civic-information project. We request an electronic extract of ${c?.label||s.court} records for ${s.start_year} through ${s.end_year}. We prefer ${s.preferred_format}. Please provide a sample file and the source-system data dictionary before the full extract if available.\n\nRequested fields:\n${fields}\n\nPlease identify how demographic fields were collected, how amended judgments are represented, and how assigned, disposition, and sentencing judges are distinguished. If any field is unavailable, please state that explicitly rather than substituting an inferred value.\n\nWe request native electronic files rather than scanned PDFs when available. Please provide an estimate before incurring fees.\n\nThank you,\nCourtScope\ninfo@courtscope.org\nhttps://courtscope.org`}
function renderRequest(){document.querySelector<HTMLElement>('#request-preview').textContent=requestText()}
document.querySelector<HTMLButtonElement>('#download-request').addEventListener('click',()=>download('courtscope-records-request.txt',requestText(),'text/plain'));document.querySelector<HTMLButtonElement>('#copy-email').addEventListener('click',async()=>{await navigator.clipboard.writeText(requestText());alert('Email copied.')});
function download(name:string,text:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function inspectFile(file:File){const ext=file.name.split('.').pop().toLowerCase();const info:{name:string,size:number,type:string,columns:string[],rows:number,status:string}={name:file.name,size:file.size,type:file.type||ext,columns:[],rows:0,status:'preserved'};if(ext==='csv'||ext==='txt'){const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);info.columns=(lines[0]||'').split(',').map(x=>x.trim().replace(/^"|"$/g,''));info.rows=Math.max(0,lines.length-1);info.status='inspected'}else if(ext==='json'){const data=JSON.parse(await file.text());const rows=Array.isArray(data)?data:(data.records||data.cases||[]);info.columns=[...new Set(rows.slice(0,50).flatMap(x=>Object.keys(x)))];info.rows=rows.length;info.status='inspected'}else if(['xlsx','xls'].includes(ext)){const zip=await JSZip.loadAsync(await file.arrayBuffer());const sharedFile=zip.file('xl/sharedStrings.xml');const shared=sharedFile?Array.from((await sharedFile.async('text')).matchAll(/<t[^>]*>(.*?)<\/t>/g)).map(m=>m[1]):[];const sheetFile=zip.file('xl/worksheets/sheet1.xml');if(!sheetFile)throw new Error('Workbook has no first worksheet');const xml=await sheetFile.async('text');const firstRow=(xml.match(/<row[^>]*r=\"1\"[^>]*>([\s\S]*?)<\/row>/)||[])[1]||'';info.columns=Array.from(firstRow.matchAll(/<c[^>]*?(?:t=\"s\")?[^>]*>[\s\S]*?<v>(.*?)<\/v>[\s\S]*?<\/c>/g)).map(m=>{const n=Number(m[1]);return Number.isInteger(n)&&shared[n]!==undefined?shared[n]:m[1]});info.rows=Math.max(0,(xml.match(/<row\b/g)||[]).length-1);info.status='inspected'}else if(ext==='zip'){const zip=await JSZip.loadAsync(await file.arrayBuffer());info.columns=Object.keys(zip.files);info.status='archive cataloged'}else if(ext==='pdf'){info.status='PDF preserved; structured companion file required for automatic mapping'}return info}
document.querySelector<HTMLInputElement>('#court-files').addEventListener('change',async (e:Event)=>{uploaded=[];const input=e.currentTarget as HTMLInputElement;for(const file of input.files||[]){try{uploaded.push(await inspectFile(file))}catch(err){const message=err instanceof Error?err.message:String(err);uploaded.push({name:file.name,size:file.size,status:`Could not inspect: ${message}`,columns:[],rows:0})}}detectedColumns=[...new Set(uploaded.flatMap(x=>x.columns))];renderFiles();renderMappings()});
function renderFiles(){document.querySelector<HTMLElement>('#file-list').innerHTML=uploaded.map(f=>`<article class="card"><strong>${f.name}</strong><p>${f.status}</p><small>${f.rows||0} rows · ${f.columns.length} detected fields · ${Math.round(f.size/1024)} KB</small></article>`).join('')}
function guess(col:string){const c=col.toLowerCase().replace(/[^a-z0-9]/g,'');const rules={case_id:['case','caseno','casenumber','indictment'],court:['court','division'],sentencing_judge:['judge','judgename','sentencingjudge'],charge_code:['charge','statute','offensecode'],offense_severity:['class','severity','felonyclass'],filing_date:['filedate','filingdate'],disposition:['disposition','outcome'],plea_trial:['plea','trial'],sentence_date:['sentencedate','sentdate'],incarceration:['sentence','months','confinement'],race:['race','racecode'],age:['age','dob','birthdate'],gender:['gender','sex'],prior_record:['prior','offenderrange','record'],updated_at:['updated','modified','amended']};for(const [key,vals] of Object.entries(rules))if(vals.some(v=>c.includes(v)))return key;return ''}
function renderMappings(){const el=document.querySelector<HTMLElement>('#mapping-list');if(!detectedColumns.length){el.innerHTML='<p class="help">No structured columns detected.</p>';return}el.innerHTML=detectedColumns.map((col,i)=>`<div class="mapping-row"><code>${col}</code><span class="mapping-arrow">→</span><select name="map_${i}" data-source="${col.replaceAll('"','&quot;')}"><option value="">Do not import</option>${canonical.map(k=>`<option value="${k}" ${guess(col)===k?'selected':''}>${k}</option>`).join('')}</select></div>`).join('')}
function renderReadiness(){const s=formState();const mappings=[...document.querySelectorAll('[name^="map_"]')].map(x=>x.value).filter(Boolean);const fields=required.map(([id,label,level])=>({id,label,level,status:s[`field_${id}`]}));const mapped=new Set(mappings);const hard=fields.filter(x=>x.level==='Required'&&x.status==='missing').map(x=>x.label);const unknown=fields.filter(x=>x.level==='Required'&&['unknown','clarify'].includes(x.status)).map(x=>x.label);const mappingRequired=canonical.filter(x=>!mapped.has(x)&&['case_id','court','sentencing_judge','charge_code','disposition','sentence_date','incarceration','race','age','prior_record'].includes(x));let status='Ready for ingestion';let cls='success';let reasons=[];if(!uploaded.length){status='Source files required';cls='error';reasons.push('Upload at least one official court file.')}if(hard.length){status='Supplemental records required';cls='error';reasons.push(`Missing required fields: ${hard.join(', ')}`)}if(unknown.length){status='Needs clarification';cls='warning';reasons.push(`Required fields still unresolved: ${unknown.join(', ')}`)}if(uploaded.length&&mappingRequired.length){status='Mapping required';cls='warning';reasons.push(`Unmapped model fields: ${mappingRequired.join(', ')}`)}document.querySelector<HTMLElement>('#readiness-summary').innerHTML=`<div class="notice ${cls}"><h3>${status}</h3><p>${reasons.join(' ')||'The source package has the minimum declared fields and mappings for a controlled ingestion dry run.'}</p></div>`;document.querySelector<HTMLElement>('#coverage-bars').innerHTML=fields.map(x=>{const pct=x.status==='available'?100:x.status==='clarify'?50:0;return `<div class="card"><strong>${x.label}</strong><div class="progress" aria-label="${pct}% ready"><span style="width:${pct}%"></span></div><small>${x.status||'unknown'} · ${x.level}</small></div>`}).join('');const report={status,jurisdiction:{city:s.city,county:s.county,state:s.state,court:s.court},files:uploaded,mappings:Object.fromEntries([...document.querySelectorAll('[name^="map_"]')].map(x=>[x.dataset.source,x.value])),field_status:Object.fromEntries(fields.map(x=>[x.id,x.status])),records_detected:uploaded.reduce((a,b)=>a+(b.rows||0),0),accepted_estimate:status==='Ready for ingestion'?uploaded.reduce((a,b)=>a+(b.rows||0),0):0,quarantined_estimate:status==='Ready for ingestion'?0:uploaded.reduce((a,b)=>a+(b.rows||0),0),generated_at:new Date().toISOString()};document.querySelector<HTMLElement>('#dry-run').textContent=JSON.stringify(report,null,2);(window as any).currentReport=report}
document.querySelector<HTMLButtonElement>('#download-project').addEventListener('click',()=>download('courtscope-city-onboarding.json',JSON.stringify({form:formState(),report:(window as any).currentReport,request:requestText()},null,2)));document.querySelector<HTMLButtonElement>('#save-project').addEventListener('click',()=>{localStorage.setItem(stateKey,JSON.stringify({form:formState(),uploaded,detectedColumns}));alert('Saved in this browser.')});
const saved=localStorage.getItem(stateKey);if(saved){try{const x=JSON.parse(saved);Object.entries(x.form||{}).forEach(([k,v])=>{const el=form.elements.namedItem(k) as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement|null;if(el)el.value=String(v)});uploaded=x.uploaded||[];detectedColumns=x.detectedColumns||[];renderFiles();renderMappings();contact()}catch{localStorage.removeItem(stateKey)}}
document.querySelector<HTMLButtonElement>('#next').addEventListener('click',()=>{if(current<steps.length-1)setStep(current+1);else renderReadiness()});document.querySelector<HTMLButtonElement>('#back').addEventListener('click',()=>setStep(current-1));
